model:
  name: "answerdotai/ModernBERT-base"
  output_dir: "checkpoints"
  max_length: 256
  dropout: 0.07

data:
  # No specific data paths needed as it uses HF datasets

training:
  epochs: 2
  batch_size: 16
  lr: 2.0e-5
  weight_decay_rate: 0.01

inference:
  # Default path, can be overridden
  model_path: "checkpoints/best_model.pt" 
  # Using the same max_length as training for consistency
  max_length: 256